version: '3'
services:
  reverse-proxy:
    image: nginx:1.17.10
    depends_on:
      - frontend
      - backend
      - minio
    volumes:
      - ./reverse_proxy/self-signed.key:/etc/ssl/self-signed.key
      - ./reverse_proxy/self-signed.crt:/etc/ssl/self-signed.crt
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
  backend:
    build:
      context: ./ams-backend
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    env_file: .env
    volumes:
      - ./ams-backend:/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
  minio:
    image: quay.io/minio/minio
    ports:
      - "9001:9001" # S3 PORT
      - "9091:9091" # HTTP PORT
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER= ${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD= ${MINIO_SECRET_KEY}
      # - MINIO_BROWSER_REDIRECT_URL=https://192.168.0.105/console/
    command: server /data --address ":9001" --console-address ":9091" --certs-dir /minio/data/certs
  frontend:
    build:
      context: ./ams-frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./ams-frontend:/front
      - /front/node_modules #Avoid re-copying local node_modules.
      - /front/.next
